FROM node:23-alpine AS builder
WORKDIR /app

COPY . /app/

RUN corepack enable
RUN corepack install

RUN pnpm install
RUN pnpm build:client

ENV NODE_ENV=production

FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Remove default Nginx configuration
RUN rm /etc/nginx/conf.d/default.conf

# Copy custom Nginx configuration
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/packages/client/dist .

CMD ["nginx", "-g", "daemon off;"]
