-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "address" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "image" TEXT NOT NULL DEFAULT '';
